services:
  editor:
    image: neovim-test
    container_name: ${CONTAINER_NAME}
    volumes:
      # maps a host path with a container path, any change made in either place will persist
      - type: bind
        source: ${BIND_MOUNT_SOURCE}
        target: ${BIND_MOUNT_TARGET}
      # persists the data of /home/vim, managed by docker
      - type: volume
        source: editor-data
        target: /home/vim
    working_dir: ${WORKING_DIR}

volumes:
  editor-data:
